apiVersion: v1
kind: Service
metadata:
  labels:
    service: frontend
  name: frontend
  namespace: udaconnect
spec:
  ports:
    - name: '3000'
      port: 3000
      targetPort: 3000
      nodePort: 30000
  selector:
    service: frontend
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend
  namespace: udaconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frontend
  template:
    metadata:
      labels:
        service: frontend
    spec:
      containers:
        - image: abdelino/udaconnect-frontend:latest
          name: frontend
          imagePullPolicy: Always
          resources:
            requests:
              memory: '512Mi'
              cpu: '256m'
            limits:
              memory: '512Mi'
              cpu: '512m'
      restartPolicy: Always
