apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: udaconnect
  labels:
    app: kafka-service
spec:
  type: ClusterIP
  selector:
    app: kafka
  ports:
    - name: '9092'
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: '9093'
      protocol: TCP
      port: 9093
      targetPort: 9093
    - name: '9094'
      protocol: TCP
      port: 9094
      targetPort: 9094
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: udaconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: docker.io/bitnami/kafka:3.9
          ports:
            - containerPort: 9092
            - containerPort: 9093
            - containerPort: 9094
          env:
            - name: KAFKA_CFG_NODE_ID
              value: '0'
            - name: KAFKA_CFG_PROCESS_ROLES
              value: 'controller,broker'
            - name: KAFKA_CFG_LISTENERS
              value: 'PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094'
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT'
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: 'PLAINTEXT://kafka-service:9092,EXTERNAL://kafka-service:9094'
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: '0@kafka-service:9093'
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: 'CONTROLLER'
            - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
              value: 'PLAINTEXT'
          volumeMounts:
            - mountPath: /bitnami/kafka
              name: kafka-data
      volumes:
        - name: kafka-data
          emptyDir: {}
