apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: locations-worker
  name: locations-worker
  namespace: udaconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      service: locations-worker
  template:
    metadata:
      labels:
        service: locations-worker
    spec:
      containers:
        - image: abdelino/udaconnect-locations-worker:v2
          name: locations-worker
          imagePullPolicy: Always
          env:
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_NAME
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_PORT
            - name: KAFKA_BROKER
              valueFrom:
                configMapKeyRef:
                  name: kafka-env
                  key: KAFKA_BROKER
            - name: KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: kafka-env
                  key: KAFKA_TOPIC
      restartPolicy: Always
