apiVersion: v1
kind: Service
metadata:
  labels:
    service: locations-grpc
  name: locations-grpc
  namespace: udaconnect
spec:
  ports:
    - name: '5000'
      port: 5000
      targetPort: 5000
      nodePort: 30002
  selector:
    service: locations-grpc
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: locations-grpc
  name: locations-grpc
  namespace: udaconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      service: locations-grpc
  template:
    metadata:
      labels:
        service: locations-grpc
    spec:
      containers:
        - image: abdelino/udaconnect-locations-grpc:v2
          name: locations-grpc
          imagePullPolicy: Always
          env:
            - name: KAFKA_BROKER
              valueFrom:
                configMapKeyRef:
                  name: kafka-env
                  key: KAFKA_BROKER
            - name: KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: kafka-env
                  key: KAFKA_TOPIC
      restartPolicy: Always
